name: Build and Push Docker Image to ACR

# This workflow runs on any push to your final submission branch
on:
  push:
    branches: [ final-submission-version ]
  workflow_dispatch: # Allows you to run it manually from the GitHub "Actions" tab

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a standard GitHub machine for the build

    steps:
    - name: 'Checkout repository code'
      uses: actions/checkout@v3

    - name: 'Log in to Azure Container Registry'
      # This step uses your AZURE_CREDENTIALS to log Docker into your private registry.
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
        password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

    - name: 'Build and push the Docker image'
      # These are standard Docker commands that will now run on the GitHub machine.
      # This completely bypasses the "ACR Tasks" restriction.
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/hackrx-app:latest .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/hackrx-app:latest