# .github/workflows/build-and-push.yml

name: Build and Push Docker Image to ACR

# This workflow will run automatically on any push to your final submission branch.
on:
  push:
    branches: [ final-submission-version ]
  # This also allows you to run it manually from the GitHub "Actions" tab if needed.
  workflow_dispatch:

jobs:
  build-and-deploy:
    # GitHub will provide a standard, powerful Linux machine for the build.
    # This completely bypasses the virtualization issue on your local machine.
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      # This step downloads your repository code onto the GitHub runner machine.
      uses: actions/checkout@v3

    - name: 'Login to Azure'
      # This step securely logs into Azure using the AZURE_CREDENTIALS secret you created.
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build and push image to ACR'
      # This is the key step. It runs the `az acr build` command on the GitHub runner.
      # It builds the Dockerfile from your repository and pushes the resulting
      # image directly to your Azure Container Registry.
      run: |
        az acr build --registry ${{ secrets.ACR_NAME }} --image hackrx-app:latest .